- name: Install zookeeper
  package:
    name: zookeeper
    state: present

- name: Install zookeeperd
  package:
    name: zookeeperd
    state: present

- name: "Download kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
  get_url:
    url: https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
    dest: "/srv/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"

- name: "Extract kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
  unarchive:
    src: "/srv/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    dest: /opt/
    remote_src: yes

- name: Add kafka group
  group:
    name: kafka
    state: present
    system: yes

- name: Add kafka user
  user:
    name: kafka
    group: kafka
    system: yes
    shell: /bin/bash
    createhome: no
    home: /var/lib/kafka
    groups:
    - kafka

- name: Create kafka home dir
  file:
    path: /var/lib/kafka
    state: directory
    owner: kafka
    group: kafka

- name: copy /lib/systemd/system/kafka.service
  template:
    src: lib/systemd/system/kafka.service
    dest: /lib/systemd/system/kafka.service
    owner: root
    group: root
    mode: 0644

- name: kafka.service reload systemd
  systemd:
    daemon_reload: yes
    name: kafka.service

- name: Enable kafka service
  service:
    name: kafka
    enabled: yes

- name: Start kafka service
  service:
    name: kafka
    state: started

- name: Copy /etc/kafka.server.properties
  template:
    src: etc/kafka.server.properties
    dest: /etc/kafka.server.properties
  notify:
  - restart kafka