- name: Clone Fake-Apache-Log-Generator git repository
  git:
    repo: https://github.com/kiritbasu/Fake-Apache-Log-Generator.git
    dest: /srv/fake-apache-log-generator
    clone: yes
    update: yes

- name: Install pip
  easy_install:
    name: pip
    state: present
    
- name: Install requirements using pip
  pip:
    requirements: /srv/fake-apache-log-generator/requirements.txt

- name: Create fake-apache-log-generator log directory
  file:
    path: /var/log/fake-apache-log-generator
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Add cron job to generate fake Apache logs
  cron:
    name: "Generate fake Apache logs"
    minute: "*/2"
    job: "/usr/bin/python /srv/fake-apache-log-generator/apache-fake-log-gen.py -n 10 -o LOG -p /var/log/fake-apache-log-generator/web"